#Variables globales
voltaje=0.0			#Inicializa el voltaje a 0.0 v
porcentaje=0.0		#Inicializa el valor del voltaje a 0 %
salir=0				#Controla la salida del modo auto o manual
driver=None			#Controlador del motor
dbexplo=None		#Base de datos de exploracion
dbtemperatura=None	#Base de datos de temperatura
dbhumedad=None		#Base de datos de humedad
dbgas=None			#Base de datos de gas
bdpresion=None		#Base de datos de presion
dbluz=None			#Base de datos de luz
dbgps=None			#Base de datos de gps
dbtiempo=None		#Base de datos de tiempo
distancia=0.0		#Distancia proporcionada por el sensor
temperatura=0.0		#Valor de la temperatura
humedad=0.0			#Valor de la humedad
gas=0				#Valor de gas
presion=0			#Valor de presion
luz=0				#Valor de luz
trigger=None		#Trigger para almacenar los datos
manu=False			#Variables para detectar modo manual
cam=None
manual=None			#Variable que carga hilo de modo manual
sdistancia=False    #Variable del sensor distancia del formulario 
stemperatura=False  #Variable del sensor temperatura del formulario
shumedad=False      #Variable del sensor humedad del formulario
sgas=False          #Variable del sensor gas del formulario
spresion=False        #Variable del sensor presion del formulario
sluz=False          #Variable del sensor luz del formulario
camara=False        #Variable de la camara del formulario
tiempo=None        	#Variable de tiempo del formulario 
nombre=False        #Variable del nombre del formulario
velocidad=30		#Variable que indica la velocidad del robot

#Funcion que inicializa las variables
def inicializar():
	voltaje=0.0			#Inicializa el voltaje a 0.0 v
	porcentaje=0.0		#Inicializa el valor del voltaje a 0 %
	salir=0				#Controla la salida del modo auto o manual
	driver=None			#Controlador del motor
	dbexplo=None		#Base de datos de exploracion
	dbtemperatura=None	#Base de datos de temperatura
	dbhumedad=None		#Base de datos de humedad
	dbgas=None			#Base de datos de gas
	dbpresion=None		#Base de datos de presion
	dbluz=None			#Base de datos de luz
	dbgps=None			#Base de datos de gps
	dbtiempo=None		#Base de datos de tiempo
	distancia=0.0		#Distancia proporcionada por el sensor
	temperatura=0.0		#Valor de la temperatura
	humedad=0.0			#Valor de la humedad
	gas=0				#Valor de gas
	presion=0				#Valor de presion
	luz=0				#Valor de luz
	trigger=None		#Trigger para almacenar los datos
	manu=False			#Variables para detectar modo manual
	cam=None			#Variable para detectar la camara
	manual=None			#Variable que carga hilo de modo manual
	sdistancia=False    #Variable del sensor distancia del formulario 
	stemperatura=False  #Variable del sensor temperatura del formulario
	shumedad=False      #Variable del sensor humedad del formulario
	sgas=False          #Variable del sensor gas del formulario
	spresion=False        #Variable del sensor presion del formulario
	sluz=False          #Variable del sensor luz del formulario
	sgps=False			#Variable del sensor gps del formulario
	camara=False        #Variable de la camara del formulario
	tiempo=None        	#Variable de tiempo del formulario 
	nombre=False        #Variable del nombre del formulario
	velocidad=30		#Variable que indica la velocidad del robot
