import RPi.GPIO as GPIO

#Variables globales
hora=' '
altitud=' '
latitud=' '
altura=' '
bot = ' '			#bot
tg = ' '			#timer de telegram
direccion = ' '
grabacion = 1			#numero de grabaciones realizadas
nombreFichero=' '		#nombre del fichero para guardar vigilancia
detectar=False			#Controla que no haya movimiento
voltaje = 0.0			#Inicializa el voltaje a 0.0 v
porcentaje = 0			#Inicializa el valor del voltaje a 0 %
salir=0				#Controla la salida del modo auto o manual
driver=0			#Controlador del motor
dbexplo=' '
dbtemperatura=' '		#Base de datos de temperatura
dbhumedad=' '			#Base de datos de humedad
dbgas=' '			#Base de datos de gas
dbluz=' '			#Base de datos de luz
dbtiempo=0			#Base de datos de tiempo
dbmovimiento=0			#Base de datos de movimiento
sensorpir=0			#Sensor HC-SR501
sensordth=0			#Sensor DTH22
sensorgas=0			#Sensor de gas
sensorluz=0			#Sensor de luz
distancia=0.0			#Distancia proporcionada por el sensor
temperatura=0.0			#Valor de la temperatura
humedad=0.0			#Valor de la humedad
gas=0				#Valor de gas
luz=0				#Valor de luz
trigger= ' '			#Trigger para almacenar los datos
timerluz=' '			#Timer para sensor de luz
timergas=' '			#Timer para sensor de gas
timerdth=' '			#Timer para sensor de DTH22
timerpir=' '			#Timer para sensor de movimiento
vigilancia=False		#Variable para detectar modo detectar movimiento
auto=False      		#Variable para detectar modo automatico
manu=False			#Variables para detectar modo manual
movimiento=' '			#Variable que carga hilo de modo detectar movimiento
automatic=' '			#Variable que carga hilo de modo automatico
manual=' '			#Variable que carga hilo de modo manual
sdistancia=False    		#Variable del sensor distancia del formulario 
stemperatura=False  		#Variable del sensor temperatura del formulario
shumedad=False      		#Variable del sensor humedad del formulario
sgas=False          		#Variable del sensor gas del formulario
sluz=False          		#Variable del sensor luz del formulario
camara=False        		#Variable de la camara del formulario
tiempo=None        		#Variable de tiempo del formulario 
nombre=False        		#Variable del nombre del formulario

#Funcion que inicializa las variables
def inicializar():
	print("inicializando variables...")
	hora=' '
	altitud=' '
	latitud=' '
	altura=' '
	grabacion = 1
	bot = ' '
	tg = ' '
	direccion = ' '
	vigilancia=False
	movimiento=' '
	timerpir=' '
	detectar=False
	salir=0
	dbtemperatura=''
	dbhumedad=''
	dbgas=''
	dbluz=''
	dbexplo=''
	sensordth=0
	sensorgas=0
	sensorluz=0
	distancia=0.0
	temperatura=0.0
	humedad=0
	gas= 0
	luz= 0
	camara= ' '
	trigger= ' '
	timerluz=' '
	timergas=' '
	timerdth=' '
	automatic=' '
	auto=False
	manual=' '
	manu=False
	sdistancia=False
	stemperatura=False
	shumedad=False
	sgas=False
	sluz=False
	camara=False
	tiempo=None
	nombre=False	
	nombreFichero=' '

