# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 09:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspirover', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensortemperatura',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
