# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspirover', '0003_sensorgps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgps',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sensorgps',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
