# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspirover', '0004_auto_20170716_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgps',
            name='lat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sensorgps',
            name='lon',
            field=models.FloatField(default=0, null=True),
        ),
    ]
